import type { ChannelsStatusSnapshot, ChannelAccountSnapshot, WeComBindingStatusResponse } from "../../api/index.js";

// OpenClaw built-in channels
export const KNOWN_CHANNELS = [
  { id: "mobile", labelKey: "nav.mobile", tutorialUrl: "", tooltip: "mobile.description" },
  { id: "telegram", labelKey: "channels.channelTelegram", tutorialUrl: "https://docs.openclaw.ai/channels/telegram", tooltip: "channels.tooltipTelegram" },
  { id: "discord", labelKey: "channels.channelDiscord", tutorialUrl: "https://docs.openclaw.ai/channels/discord", tooltip: "channels.tooltipDiscord" },
  { id: "slack", labelKey: "channels.channelSlack", tutorialUrl: "https://docs.openclaw.ai/channels/slack", tooltip: "channels.tooltipSlack" },
  { id: "googlechat", labelKey: "channels.channelGoogleChat", tutorialUrl: "https://docs.openclaw.ai/channels/googlechat", tooltip: "channels.tooltipGoogleChat" },
  { id: "signal", labelKey: "channels.channelSignal", tutorialUrl: "https://docs.openclaw.ai/channels/signal", tooltip: "channels.tooltipSignal" },
  { id: "imessage", labelKey: "channels.channelIMessage", tutorialUrl: "https://docs.openclaw.ai/channels/imessage", tooltip: "channels.tooltipIMessage" },
  { id: "feishu", labelKey: "channels.channelFeishu", tutorialUrl: "https://docs.openclaw.ai/channels/feishu", tooltip: "channels.tooltipFeishu" },
  { id: "line", labelKey: "channels.channelLine", tutorialUrl: "https://docs.openclaw.ai/channels/line", tooltip: "channels.tooltipLine" },
  { id: "matrix", labelKey: "channels.channelMatrix", tutorialUrl: "https://docs.openclaw.ai/channels/matrix", tooltip: "channels.tooltipMatrix" },
  { id: "mattermost", labelKey: "channels.channelMattermost", tutorialUrl: "https://docs.openclaw.ai/channels/mattermost", tooltip: "channels.tooltipMattermost" },
  { id: "msteams", labelKey: "channels.channelMsteams", tutorialUrl: "https://docs.openclaw.ai/channels/msteams", tooltip: "channels.tooltipMsteams" },
] as const;

// Channels that require services blocked in mainland China (GFW)
export const CHINA_BLOCKED_CHANNELS = new Set([
  "telegram", "discord", "signal", "line", "googlechat", "slack",
]);

export function StatusBadge({ status, t }: { status: boolean | null | undefined; t: (key: string) => string }) {
  const variant = status === true ? "badge-success" : status === false ? "badge-danger" : "badge-warning";
  const text = status === true ? t("channels.statusYes") : status === false ? t("channels.statusNo") : t("channels.statusUnknown");

  return (
    <span className={`badge ${variant}`}>
      {text}
    </span>
  );
}

/** Filter KNOWN_CHANNELS by locale (hide GFW-blocked channels for zh users). */
export function getVisibleChannels(lang: string, selectedDropdownChannel: string) {
  return lang === "zh"
    ? KNOWN_CHANNELS.filter(ch => !CHINA_BLOCKED_CHANNELS.has(ch.id) || ch.id === selectedDropdownChannel)
    : [...KNOWN_CHANNELS];
}

export interface AccountEntry {
  channelId: string;
  channelLabel: string;
  account: ChannelAccountSnapshot;
  isWecom?: boolean;
}

/** Build the unified accounts list from snapshot + WeCom status, filtering synthetic defaults. */
export function buildAccountsList(
  snapshot: ChannelsStatusSnapshot,
  wecomStatus: WeComBindingStatusResponse | null,
  t: (key: string) => string,
): AccountEntry[] {
  const allAccounts: AccountEntry[] = [];

  // Add WeCom virtual account if relay connection exists
  if (wecomStatus && wecomStatus.connected) {
    allAccounts.push({
      channelId: "wecom",
      channelLabel: t("channels.channelWecom"),
      isWecom: true,
      account: {
        accountId: "default",
        name: t("channels.channelWecom"),
        configured: !!wecomStatus.externalUserId,
        running: true,
        enabled: true,
        dmPolicy: "pairing",
      } as ChannelAccountSnapshot,
    });
  }

  for (const [channelId, accounts] of Object.entries(snapshot.channelAccounts)) {
    // WeCom is handled as a virtual account above. Skip its raw gateway entries.
    if (channelId === "wechat") continue;

    const knownChannel = KNOWN_CHANNELS.find(c => c.id === channelId);
    const channelLabel = knownChannel ? t(knownChannel.labelKey) : snapshot.channelLabels[channelId] || channelId;

    for (const account of accounts) {
      // Skip synthetic "default" placeholder accounts (auto-generated by gateway when no config exists)
      const isSyntheticDefault =
        account.accountId === "default" &&
        account.configured === false &&
        !account.name &&
        (account as any).tokenSource === "none";

      if (isSyntheticDefault) continue;
      allAccounts.push({ channelId, channelLabel, account });
    }
  }

  return allAccounts;
}
